spring:
  profiles:
    active: dev
 # rabbitmq:
 #   host: 47.96.173.142
 #   port: 5672
  #  username: guest
  #  password: guest
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: IRP
    password: IRP
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
irmcloud:
  server:
    eureka:
      port: 8761
      hostname: irmcloud-eureka
      serviceUrl: http://root:root@localhost:8761/eureka/
    configserver:
      port: 8080
      hostname: irmcloud-configserver
      serviceUrl: http://admin:admin@localhost:8080
    gateway:
      port: 7979
      hostname: irmcloud-gateway
    provider:
      uac:
        port: 8000
        hostname: irmcloud-provider-uac
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
