spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.33.145:1521:ORCL 
paascloud:
  auth:
    rest-pwd-url: http://dev-login.paascloud.net/resetPwd?resetPwdKey=
    active-user-url: http://dev-api.paascloud.net:7979/uac/auth/activeUser/
    refresh-token-url: http://dev-api.paascloud.net:7979/uac/oauth/token